version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: processgpt-db
    environment:
      POSTGRES_DB: processgpt
      POSTGRES_USER: processgpt
      POSTGRES_PASSWORD: processgpt123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
